name: CI-CD Using appleboy-ssh-action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME  }}
          username: ${{ secrets.USER_NAME  }}
          key: ${{ secrets.AWS_PRIVATE_KEY  }}
          script: |
            ls -la
            cd /home/ubuntu/katteri_proyek2/
            git pull
            docker-compose up -d --build

# name: Deploy to EC2
#
# on:
#   push:
